### PR TITLE
Update categories.json

### PR DESCRIPTION
**Pull request by Delicious-Bacon**
Sort and add new categories.
```
"7": "Mods (require HL1)"
"10": "Demos"
"12": "HDR available"
"21": "Downloadable Content"
"33": "Native Steam Controller"
"41": "Remote Play on Phone"
"42": "Remote Play on Tablet"
"43": "Remote Play on TV"
"44": "Remote Play Together"
"45": "Cloud Gaming"
"46": "Cloud Gaming (NVIDIA)"
"47": "LAN PvP"
"48": "LAN Co-op"
"49": "PvP"
"50": "Additional High-Quality Audio"
"51": "Steam Workshop"
"52": "Tracked Controller Support"
"53": "VR Supported"
"54": "VR Only"
```

### CODE REVIEW

**Comment by woctezuma** [comment]
Thank you!

For the record, this patch adds 4 categories:

```diff
+ "7": "Mods (require HL1)",
+ "10": "Demos",
+ "12": "HDR available",
+ "21": "Downloadable Content",
+ "33": "Native Steam Controller",
+ "41": "Remote Play on Phone",
+ "42": "Remote Play on Tablet",
+ "43": "Remote Play on TV",
+ "44": "Remote Play Together",
+ "45": "Cloud Gaming",
+ "46": "Cloud Gaming (NVIDIA)",
+ "47": "LAN PvP",
+ "48": "LAN Co-op",
+ "49": "PvP",
+ "50": "Additional High-Quality Audio",
+ "51": "Steam Workshop",
+ "52": "Tracked Controller Support",
```

expands 1 category:

```diff
- "31": "VR Support",
+ "53": "VR Supported",
+ "54": "VR Only",
```

and replaces 3 categories:

```diff
- "36": "Online Multi-Player",
- "37": "Local Multi-Player",
- "39": "Local Co-op",
+ "36": "Online PvP",
+ "37": "Shared/Split Screen PvP",
+ "39": "Shared/Split Screen Co-op",
```

which are complemented by 3 of the added categories mentioned above:

```diff
+ "47": "LAN PvP",
+ "48": "LAN Co-op",
+ "49": "PvP",
```

**Comment by woctezuma** [comment]
I have re-added the category "VR Support" (n°31) with the following commit:
- https://github.com/woctezuma/steam-api/commit/0cd3a90ed2d81b261dd4b967f2909d50d0f0b3cd ` Re-add the category "VR Support" `

**Comment by woctezuma** [comment]
For info, there is [this API endpoint](https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Store-Categories). Maybe you already knew about it.

```
GET https://store.steampowered.com/actions/ajaxgetstorecategories
```

There is also a similar [API endpoint](https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Store-Tags) for store tags.

```
GET https://store.steampowered.com/actions/ajaxgetstoretags
```

I don't think there is one for genres.

**Comment by Delicious-Bacon** [comment]
> For info, ...

Yeah, I was aware of the endpoints, but neither give full info. :sweat_smile:

**Pull request merged**
